# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passwd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('1', 'APP'), ('2', '网站'), ('3', '银行卡'), ('4', '信用卡'), ('5', '运维')], default='1', max_length=2)),
                ('name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('website', models.CharField(max_length=40)),
                ('mark', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '密码',
                'verbose_name_plural': '密码',
            },
        ),
    ]
