# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nami', '0002_auto_20171105_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwd',
            name='website',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
