# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nami', '0003_auto_20171115_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField()),
                ('trans_bal', models.FloatField()),
                ('payment_way', models.CharField(choices=[('1', '现金'), ('2', '支付宝'), ('3', '花呗'), ('4', '微信'), ('5', '京东白条'), ('6', '银行卡'), ('7', '信用卡')], max_length=10)),
                ('pay_status', models.CharField(choices=[('0', '未支付'), ('1', '已支付')], max_length=10)),
                ('remarks', models.CharField(max_length=50, verbose_name='备注')),
            ],
            options={
                'verbose_name': '消费记录',
                'verbose_name_plural': '消费记录',
            },
        ),
        migrations.CreateModel(
            name='LoanDTL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField()),
                ('loan_amount', models.FloatField()),
                ('rate_amount', models.FloatField()),
                ('loan_length', models.IntegerField(verbose_name='贷款期限（月数）')),
                ('loan_balance', models.FloatField()),
                ('close_flag', models.CharField(choices=[('0', '未结清'), ('1', '已结清')], max_length=10)),
                ('loan_purpose', models.CharField(max_length=50, verbose_name='贷款用途')),
                ('loan_begin_date', models.DateField()),
                ('loan_end_date', models.DateField()),
            ],
            options={
                'verbose_name': '消费记录',
                'verbose_name_plural': '消费记录',
            },
        ),
    ]
