# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nami', '0004_expenserecords_loandtl'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField()),
                ('trans_bal', models.FloatField()),
                ('income_resource', models.CharField(choices=[('1', '工资'), ('2', '微信红包')], max_length=15)),
            ],
            options={
                'verbose_name': '收入明细',
                'verbose_name_plural': '收入明细',
            },
        ),
    ]
