# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nami', '0005_incomerecords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanDTL',
            new_name='LoanCreditDTL',
        ),
        migrations.AlterField(
            model_name='incomerecords',
            name='income_resource',
            field=models.CharField(choices=[('1', '现金'), ('2', '工资'), ('3', '公积金'), ('4', '医保'), ('5', '微信红包')], max_length=15),
        ),
    ]
