# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nami', '0006_auto_20171211_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenserecords',
            name='pay_status',
        ),
    ]
