# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BigClass', models.CharField(choices=[('Luffy', '路飞'), ('Zoro', '索隆'), ('Sanji', '山治'), ('Franky', '弗兰克'), ('Robin', '罗宾')], max_length=10)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
