# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luffy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thefunctions',
            name='name',
        ),
        migrations.AddField(
            model_name='members',
            name='scope',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.CharField(choices=[('1', 'Luffy'), ('2', 'Zoro'), ('3', 'Sanji'), ('4', 'Usopp'), ('5', 'Nami'), ('6', 'Chopper'), ('7', 'Robin'), ('8', 'Franky'), ('9', 'Brook'), ('10', 'Jinbe'), ('11', 'Sunny')], max_length=10),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(choices=[('1', 'Luffy'), ('2', 'Zoro'), ('3', 'Sanji'), ('4', 'Usopp'), ('5', 'Nami'), ('6', 'Chopper'), ('7', 'Robin'), ('8', 'Franky'), ('9', 'Brook'), ('10', 'Jinbe'), ('11', 'Sunny')], max_length=10),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffy.Members'),
        ),
        migrations.DeleteModel(
            name='TheFunctions',
        ),
    ]
