# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luffy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='name',
        ),
        migrations.AddField(
            model_name='todolist',
            name='ExecAddress',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='ExecTime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='SubClass',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='Tasks',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='BigClass',
            field=models.CharField(choices=[('Luffy', '路飞'), ('Zoro', '索隆'), ('Sanji', '山治'), ('Usopp', '乌索普'), ('Nami', '娜美'), ('Chopper', '乔巴'), ('Robin', '罗宾'), ('Franky', '弗兰克'), ('Brook', '布鲁克'), ('Jinbe', '甚平'), ('Sunny', '桑尼')], max_length=10),
        ),
    ]
