# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luffy', '0002_auto_20171115_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'TodoList', 'verbose_name_plural': 'TodoList'},
        ),
        migrations.AlterField(
            model_name='todolist',
            name='scope',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
