# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luffy', '0002_auto_20170918_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='BigClass',
            new_name='big_class',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='created',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='ExecAddress',
            new_name='exec_address',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='ExecTime',
            new_name='exec_time',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='SubClass',
            new_name='sub_class',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='Tasks',
            new_name='tasks',
        ),
        migrations.AddField(
            model_name='todolist',
            name='progress_rate',
            field=models.FloatField(default=0),
        ),
    ]
