# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luffy', '0004_auto_20170918_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='big_class',
            field=models.CharField(choices=[('1', 'Luffy'), ('2', 'Zoro'), ('3', 'Sanji'), ('4', 'Usopp'), ('5', 'Nami'), ('6', 'Chopper'), ('7', 'Robin'), ('8', 'Franky'), ('9', 'Brook'), ('10', 'Jinbe'), ('11', 'Sunny')], max_length=10),
        ),
    ]
