# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luffy', '0004_auto_20171115_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.CharField(choices=[('1', 'Luffy'), ('2', 'Zoro'), ('3', 'Sanji'), ('4', 'Usopp'), ('5', 'Nami'), ('6', 'Chopper'), ('7', 'Robin'), ('8', 'Franky'), ('9', 'Brook'), ('10', 'Jinbe')], max_length=10),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(choices=[('1', 'Luffy'), ('2', 'Zoro'), ('3', 'Sanji'), ('4', 'Usopp'), ('5', 'Nami'), ('6', 'Chopper'), ('7', 'Robin'), ('8', 'Franky'), ('9', 'Brook'), ('10', 'Jinbe')], max_length=10),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
