# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luffy', '0005_auto_20171115_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
