# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luffy', '0005_auto_20170920_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='task_list',
            field=models.TextField(null=True),
        ),
    ]
