# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 16:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luffy', '0007_remove_todolist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='end_date',
            field=models.DateField(default=datetime.date(2100, 12, 31)),
        ),
    ]
