# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luffy', '0009_auto_20171126_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='exec_date',
        ),
    ]
