# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luffy', '0011_auto_20171204_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-important'], 'verbose_name': 'TodoList', 'verbose_name_plural': 'TodoList'},
        ),
    ]
