# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luffy', '0012_auto_20171204_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheFunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '职能',
                'verbose_name_plural': '职能',
            },
        ),
        migrations.RemoveField(
            model_name='members',
            name='scope',
        ),
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffy.TheFunctions'),
        ),
        migrations.AddField(
            model_name='thefunctions',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffy.Members'),
        ),
    ]
