# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luffy', '0013_auto_20171212_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='label',
            field=models.CharField(default=None, max_length=50, verbose_name='标签'),
        ),
    ]
