# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoro', '0002_journey_spend'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitness',
            name='place',
            field=models.CharField(choices=[('gym', '健身房'), ('home', '在家')], default='gym', max_length=10),
        ),
    ]
