# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoro', '0003_fitness_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cycling',
            options={'verbose_name': '骑行', 'verbose_name_plural': '骑行'},
        ),
        migrations.AlterModelOptions(
            name='fitness',
            options={'verbose_name': '健身', 'verbose_name_plural': '健身'},
        ),
        migrations.AlterModelOptions(
            name='journey',
            options={'verbose_name': '旅行', 'verbose_name_plural': '旅行'},
        ),
    ]
