# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoro', '0006_auto_20171121_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness',
            name='place',
            field=models.CharField(choices=[('gym', '健身房'), ('home', '在家'), ('outdoor', '户外')], default='gym', max_length=10),
        ),
    ]
