# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoro', '0008_auto_20171202_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycling',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
