# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoro', '0009_auto_20171202_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycling',
            name='route',
            field=models.ImageField(upload_to='zoro/cycling/'),
        ),
    ]
